"""initial schema

Revision ID: b8e88b4ebf48
Revises: 
Create Date: 2026-05-09 10:41:41.240619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e88b4ebf48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('pricing_strategy', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_code'), 'platforms', ['code'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('base_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('raw_specs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('product_platform_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('ai_generated_title', sa.String(length=255), nullable=True),
    sa.Column('ai_generated_desc', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('floor_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ceiling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('competitor_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('has_buybox', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'platform_id', name='uq_product_platform')
    )
    op.create_index(op.f('ix_product_platform_status_external_id'), 'product_platform_status', ['external_id'], unique=False)
    op.create_table('pricing_agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_platform_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=32), nullable=False),
    sa.Column('trigger_event', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_platform_id'], ['product_platform_status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_agent_logs_created_at'), 'pricing_agent_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pricing_agent_logs_product_platform_id'), 'pricing_agent_logs', ['product_platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_agent_logs_product_platform_id'), table_name='pricing_agent_logs')
    op.drop_index(op.f('ix_pricing_agent_logs_created_at'), table_name='pricing_agent_logs')
    op.drop_table('pricing_agent_logs')
    op.drop_index(op.f('ix_product_platform_status_external_id'), table_name='product_platform_status')
    op.drop_table('product_platform_status')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_platforms_code'), table_name='platforms')
    op.drop_table('platforms')
    # ### end Alembic commands ###
